// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// BaseRequest base request
//
// swagger:discriminator baseRequest @type
type BaseRequest interface {
	runtime.Validatable
	runtime.ContextValidatable

	// at type
	AtType() string
	SetAtType(string)

	// AdditionalProperties in base type shoud be handled just like regular properties
	// At this moment, the base type property is pushed down to the subtype
}

type baseRequest struct {
	atTypeField string
}

// AtType gets the at type of this polymorphic type
func (m *baseRequest) AtType() string {
	return "baseRequest"
}

// SetAtType sets the at type of this polymorphic type
func (m *baseRequest) SetAtType(val string) {
}

// UnmarshalBaseRequestSlice unmarshals polymorphic slices of BaseRequest
func UnmarshalBaseRequestSlice(reader io.Reader, consumer runtime.Consumer) ([]BaseRequest, error) {
	var elements []json.RawMessage
	if err := consumer.Consume(reader, &elements); err != nil {
		return nil, err
	}

	var result []BaseRequest
	for _, element := range elements {
		obj, err := unmarshalBaseRequest(element, consumer)
		if err != nil {
			return nil, err
		}
		result = append(result, obj)
	}
	return result, nil
}

// UnmarshalBaseRequest unmarshals polymorphic BaseRequest
func UnmarshalBaseRequest(reader io.Reader, consumer runtime.Consumer) (BaseRequest, error) {
	// we need to read this twice, so first into a buffer
	data, err := io.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	return unmarshalBaseRequest(data, consumer)
}

func unmarshalBaseRequest(data []byte, consumer runtime.Consumer) (BaseRequest, error) {
	buf := bytes.NewBuffer(data)
	buf2 := bytes.NewBuffer(data)

	// the first time this is read is to fetch the value of the @type property.
	var getType struct {
		AtType string `json:"@type"`
	}
	if err := consumer.Consume(buf, &getType); err != nil {
		return nil, err
	}

	if err := validate.RequiredString("@type", "body", getType.AtType); err != nil {
		return nil, err
	}

	// The value of @type is used to determine which type to create and unmarshal the data into
	switch getType.AtType {
	case "baseRequest":
		var result baseRequest
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil
	case "writeRequest":
		var result WriteRequest
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil
	}
	return nil, errors.New(422, "invalid @type value: %q", getType.AtType)
}

// Validate validates this base request
func (m *baseRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this base request based on context it is used
func (m *baseRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
